version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./.dockervenv:/src/.venv
      - ./api:/src
    ports:
      - 3000:8000
    tty: true
    stdin_open: true
  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    ports:
      - 8000:3000
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true
volumes:
  postgres_data:
  
