version: '3'

services:
  api-prod:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    volumes:
      - ./.dockervenv:/src/.venv
      - ./api:/src
    ports:
      - '8000'
    tty: true
    stdin_open: true

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    restart: always
    ports:
      - 8000:80
    depends_on:
      - api-prod

volumes:
  postgres_data:
  tmp-data:
