FROM python:3.11-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN mkdir -p tmp

RUN pip install poetry

COPY pyproject.toml* poetry.lock* ./

RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

COPY . .

VOLUME /src
VOLUME /src/tmp

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--uds", "tmp/uvicorn.sock"]
